---
# LXD container options
containers: 
  - 'dev'

container_image: '20.04'
profiles: ["default"]
server: 'https://cloud-images.ubuntu.com/releases'
protocol: 'simplestreams'
is_ephemeral: yes

install_packages: true
container_packages:
  - fish
  - yadm
  - python3-virtualenv
  - ranger
  - kitty-terminfo
  - emacs-nox
  - ranger
  - tmux
  - jq
  - python3-autopep8
  - elpa-py-autopep8

# run post setup commands
post_setup: false
post_commands:
  # add a cache server, etc.
  - ''
  
# dot files
use_dotfiles: false
dotfile_path: ''
dotfile_url: ''
clone_commands:
  - lxc exec "{{ container_name }}" git clone '{{ dotfile_url }}'

# directory mounts
enable_mounts: false
mount_name: 
  - 'data'
mount_path_host: 
  - ''
mount_path_lxc:
  - '/data'
