---
# LXD container options
container_name: 'workspace'
container_image: '20.04'
profiles: ["default"]
server: 'https://cloud-images.ubuntu.com/releases'
protocol: 'simplestreams'


# install packages
install_packages: false
container_packages:
  - ansible
  - yadm


# run post setup commands
post_setup: false
post_commands:
  # add a cache server, etc.
  - lxc exec "{{ container_name }}" -- bash -c "ls"
  

# dot files
use_dotfiles: false
dotfile_path: '/root/dotfiles'
dotfile_url: 'url_here'
clone_commands:
  - lxc exec "{{ container_name }}" git clone '{{ dotfile_url }}'


# directory mounts
enable_mounts: false
mount1_name: 'projects'
mount1_path_host: '/your/projects'
mount1_path_lxc: '/projects'
